openapi:
  aprtment:
    base-url: http://openapi.molit.go.kr
    data-url: OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev
    service-key: Y2UOCkD8Ilv2gViPGV33ddNTTQfRi92i8mRzUeQX%2BNgSiNTO3gp9hJZX4J6u8uXucMM6RdRBoGxMn6XHfsEzNA%3D%3D


app:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-scheme-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresh-token-expiry: 1296000000


file:
  dir: D:/download/greengram4/


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram5
    username: root
    password: green502
    driven-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: wgg9h0L_cA5idmf8OTnE
            clientSecret: gXfkSuuerE
            scope:
              - email
              - profile
          facebook:
            clientId: wWj9h0L_cA5idmf8OTnE
            clientSecret: wXMkSuuerE
            scope:
              - email
              - public_profile
          naver:
            client-id: wWj9h0L_cA5IuMF8OTnE
            client-secret: wXMkSHeUWE
            #clientAuthenticationMethod: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/naver
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: 0d2c5351cfbede3dd7094bdee8b6d56a
            client-secret: Qj4qbd8xNE3jjBECgi7lCKd2z3neR0jo
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            #redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            redirectUri: http://localhost:8082/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
            clientName: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8082

fcm:
  certification: serviceAccountKey.json

logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off

---

spring:
  config:
    activate:
      on-profile: "prod1"

file:
  dir: /home/download/
server:
  port: 8083

---

spring:
  config:
    activate:
      on-profile: "prod2"
server:
  port: 8084